const produtos = [
    {
        codigo: "001",
        nome: "Projetor HY300 Smart Android 11 4K",
        descricao: "Projetor portátil com Android 11, Wi-Fi 6 e rotação 180°. Resolução 4K real com foco automático.",
        imagem: "https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=400&h=400&fit=crop",
        categoria: "eletronicos",
        precoOriginal: 599.90,
        precoAtual: 349.90,
        badge: "🔥 Mais Vendido",
        avaliacao: 4.8,
        vendidos: 2340,
        linkShopee: "https://shope.ee/projetor-hy300",
        linkAmazon: "https://amzn.to/projetor-hy300",
        linkMercadoLivre: "https://mercadolivre.com.br/projetor-hy300"
    },
    {
        codigo: "002",
        nome: "Fone Bluetooth Lenovo LP40 Pro TWS",
        descricao: "Áudio estéreo HD, Bluetooth 5.1, 20h de bateria total. Ultraleve com cancelamento de ruído.",
        imagem: "https://images.unsplash.com/photo-1590658268037-6bf12f032f55?w=400&h=400&fit=crop",
        categoria: "eletronicos",
        precoOriginal: 129.90,
        precoAtual: 59.90,
        badge: "⚡ Oferta Relâmpago",
        avaliacao: 4.6,
        vendidos: 8920,
        linkShopee: "https://shope.ee/lenovo-lp40",
        linkAmazon: "",
        linkMercadoLivre: "https://mercadolivre.com.br/lenovo-lp40"
    },
    {
        codigo: "003",
        nome: "Smartwatch Ultra Serie 9 com NFC",
        descricao: "Tela AMOLED 2.2\", NFC, chamadas Bluetooth, monitoramento cardíaco e SpO2. À prova d'água IP68.",
        imagem: "https://images.unsplash.com/photo-1546868871-af0de0ae72be?w=400&h=400&fit=crop",
        categoria: "eletronicos",
        precoOriginal: 249.90,
        precoAtual: 129.90,
        badge: "🆕 Lançamento",
        avaliacao: 4.7,
        vendidos: 5430,
        linkShopee: "https://shope.ee/smartwatch-ultra9",
        linkAmazon: "https://amzn.to/smartwatch-ultra9",
        linkMercadoLivre: ""
    },
    {
        codigo: "004",
        nome: "Umidificador Efeito Chama Flame 3D",
        descricao: "Difusor de aromas com efeito realista de chama LED. Silencioso, ideal para relaxar e decorar.",
        imagem: "https://images.unsplash.com/photo-1602607615953-d7c0e5a4cd47?w=400&h=400&fit=crop",
        categoria: "casa",
        precoOriginal: 159.90,
        precoAtual: 89.90,
        badge: "🏠 Queridinho",
        avaliacao: 4.9,
        vendidos: 3210,
        linkShopee: "https://shope.ee/umidificador-flame",
        linkAmazon: "https://amzn.to/umidificador-flame",
        linkMercadoLivre: ""
    },
    {
        codigo: "005",
        nome: "Mini Processador Alimentos USB 250ml",
        descricao: "Triture alho, cebola e temperos em segundos. Recarregável via USB-C, lâminas de aço inox.",
        imagem: "https://images.unsplash.com/photo-1585515320310-259814833e62?w=400&h=400&fit=crop",
        categoria: "casa",
        precoOriginal: 79.90,
        precoAtual: 35.90,
        badge: "⚡ Oferta Relâmpago",
        avaliacao: 4.5,
        vendidos: 12400,
        linkShopee: "https://shope.ee/mini-processador",
        linkAmazon: "",
        linkMercadoLivre: "https://mercadolivre.com.br/mini-processador"
    },
    {
        codigo: "006",
        nome: "Escova Secadora Alisadora 3em1 1200W",
        descricao: "Seca, alisa e modela em uma passada. Cerâmica com turmalina, gera íons negativos anti-frizz.",
        imagem: "https://images.unsplash.com/photo-1522338242992-e1a54f55ed4b?w=400&h=400&fit=crop",
        categoria: "beleza",
        precoOriginal: 189.90,
        precoAtual: 79.90,
        badge: "🔥 Mais Vendido",
        avaliacao: 4.8,
        vendidos: 15600,
        linkShopee: "https://shope.ee/escova-secadora",
        linkAmazon: "https://amzn.to/escova-secadora",
        linkMercadoLivre: "https://mercadolivre.com.br/escova-secadora"
    },
    {
        codigo: "007",
        nome: "Câmera Segurança Wi-Fi A8 Externa IP66",
        descricao: "Visão noturna colorida, detecção de movimento com alerta no app. Prova d'água para áreas externas.",
        imagem: "https://images.unsplash.com/photo-1558002038-1055907df827?w=400&h=400&fit=crop",
        categoria: "eletronicos",
        precoOriginal: 199.90,
        precoAtual: 115.00,
        badge: "🛡️ Segurança",
        avaliacao: 4.4,
        vendidos: 6780,
        linkShopee: "https://shope.ee/camera-a8-wifi",
        linkAmazon: "",
        linkMercadoLivre: "https://mercadolivre.com.br/camera-a8"
    },
    {
        codigo: "008",
        nome: "Kit 4 Organizadores Geladeira Acrílico",
        descricao: "Empilháveis e transparentes. Otimize espaço e conserve alimentos com estilo. Fácil de limpar.",
        imagem: "https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=400&h=400&fit=crop",
        categoria: "casa",
        precoOriginal: 149.90,
        precoAtual: 95.90,
        badge: "",
        avaliacao: 4.3,
        vendidos: 4560,
        linkShopee: "https://shope.ee/organizador-geladeira",
        linkAmazon: "https://amzn.to/organizador-geladeira",
        linkMercadoLivre: ""
    },
    {
        codigo: "009",
        nome: "Massageador Pescoço Eletromagnético",
        descricao: "Alívio instantâneo de tensão e dor. Pulsos eletromagnéticos com aquecimento. Portátil e recarregável.",
        imagem: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=400&h=400&fit=crop",
        categoria: "saude",
        precoOriginal: 99.90,
        precoAtual: 45.00,
        badge: "⚡ Oferta Relâmpago",
        avaliacao: 4.6,
        vendidos: 7890,
        linkShopee: "https://shope.ee/massageador-pescoco",
        linkAmazon: "",
        linkMercadoLivre: ""
    },
    {
        codigo: "010",
        nome: "Kit Maquiagem Completo Profissional",
        descricao: "Maleta com 120 cores de sombra, blushes, batons, pincéis e primer. Presente perfeito.",
        imagem: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400&h=400&fit=crop",
        categoria: "beleza",
        precoOriginal: 289.90,
        precoAtual: 189.90,
        badge: "🆕 Lançamento",
        avaliacao: 4.7,
        vendidos: 3450,
        linkShopee: "https://shope.ee/kit-maquiagem",
        linkAmazon: "",
        linkMercadoLivre: "https://mercadolivre.com.br/kit-maquiagem"
    },
    {
        codigo: "011",
        nome: "Ring Light 26cm LED com Tripé 2.1m",
        descricao: "Iluminação profissional para lives, fotos e vídeos. 3 modos de luz, 10 níveis de brilho. Suporte celular.",
        imagem: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=400&h=400&fit=crop",
        categoria: "eletronicos",
        precoOriginal: 139.90,
        precoAtual: 69.90,
        badge: "⚡ Oferta Relâmpago",
        avaliacao: 4.5,
        vendidos: 9200,
        linkShopee: "https://shope.ee/ring-light-26",
        linkAmazon: "https://amzn.to/ring-light",
        linkMercadoLivre: ""
    },
    {
        codigo: "012",
        nome: "Aspirador Robô Inteligente 3em1",
        descricao: "Varre, aspira e passa pano automaticamente. Sensores anti-queda e mapeamento inteligente.",
        imagem: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=400&h=400&fit=crop",
        categoria: "casa",
        precoOriginal: 499.90,
        precoAtual: 279.90,
        badge: "🔥 Mais Vendido",
        avaliacao: 4.4,
        vendidos: 6100,
        linkShopee: "https://shope.ee/aspirador-robo",
        linkAmazon: "https://amzn.to/aspirador-robo",
        linkMercadoLivre: "https://mercadolivre.com.br/aspirador-robo"
    },
    {
        codigo: "013",
        nome: "Garrafa Térmica Smart LED 500ml",
        descricao: "Mostra temperatura no display LED. Inox dupla parede, mantém quente 12h ou gelado 24h.",
        imagem: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400&h=400&fit=crop",
        categoria: "casa",
        precoOriginal: 89.90,
        precoAtual: 42.90,
        badge: "",
        avaliacao: 4.3,
        vendidos: 11200,
        linkShopee: "https://shope.ee/garrafa-termica-led",
        linkAmazon: "",
        linkMercadoLivre: "https://mercadolivre.com.br/garrafa-led"
    },
    {
        codigo: "014",
        nome: "Kit Skincare Coreano 5 Passos",
        descricao: "Limpeza, tônico, sérum, hidratante e protetor. Pele de porcelana com rotina completa K-beauty.",
        imagem: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=400&h=400&fit=crop",
        categoria: "beleza",
        precoOriginal: 159.90,
        precoAtual: 89.90,
        badge: "🆕 Lançamento",
        avaliacao: 4.9,
        vendidos: 4320,
        linkShopee: "https://shope.ee/skincare-coreano",
        linkAmazon: "",
        linkMercadoLivre: ""
    },
    {
        codigo: "015",
        nome: "Balança Digital Corporal Bluetooth",
        descricao: "Mede peso, gordura, massa muscular e mais 10 métricas. Sincroniza com app no celular.",
        imagem: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=400&h=400&fit=crop",
        categoria: "saude",
        precoOriginal: 119.90,
        precoAtual: 54.90,
        badge: "⚡ Oferta Relâmpago",
        avaliacao: 4.5,
        vendidos: 8900,
        linkShopee: "https://shope.ee/balanca-bluetooth",
        linkAmazon: "https://amzn.to/balanca-bt",
        linkMercadoLivre: ""
    },
    {
        codigo: "016",
        nome: "Fita LED RGB Wi-Fi 5 Metros",
        descricao: "Controle por app e voz (Alexa/Google). 16 milhões de cores, música reativa. Adesiva, fácil instalação.",
        imagem: "https://images.unsplash.com/photo-1550535424-b498819c7572?w=400&h=400&fit=crop",
        categoria: "casa",
        precoOriginal: 79.90,
        precoAtual: 39.90,
        badge: "🏠 Queridinho",
        avaliacao: 4.6,
        vendidos: 14300,
        linkShopee: "https://shope.ee/fita-led-wifi",
        linkAmazon: "https://amzn.to/fita-led-rgb",
        linkMercadoLivre: "https://mercadolivre.com.br/fita-led"
    }
];

export default produtos;
